server:
  port: ${PORT:7980}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
