server:
    port: ${PORT:8889}
    contextPath: /uaa
    
security:
    basic.enabled: false
    ignored: /css/**,/js/**,/favicon.ico,/webjars/**,/console/**

jwt.keystore:
    alias: webb-oauth-server
    password: capella

logging.level:
    org.springframework.security=DEBUG
    
spring:
    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:~/h2-data/webb-oauth-server;AUTO_SERVER=TRUE
        databaseName:
        serverName:
        username:
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false