turbine:
  appConfig: capella-webb
  clusterNameExpression: 'default'

server:
  port: ${PORT:8989}
  
management:
  port: ${MANAGEMENT_PORT:8990}
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761}/eureka/    